name: 3dgs-avatar
channels:
  - pytorch3d
  - pytorch
  - iopath
  - fvcore
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - ffmpeg=4.2.2
  - fvcore=0.1.5
  - iopath=0.1.9
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - pytorch3d=0.7.1
  - torchaudio=0.12.1
  - torchmetrics=0.11.4
  - torchvision=0.13.1
  - trimesh=3.23.5
  - tqdm
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - hydra-core==1.3.2
      - libigl==2.4.1
      - imageio==2.31.2
      - lpips==0.1.4
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - scikit-image==0.19.3
#      - tinycudann==1.7
      - wandb==0.15.11
