# @package _global_

non_rigid_name: ingp

model:
  deformer:
    non_rigid:
      name: hashgrid
      scale_offset: logit
      rot_offset: mult

      delay: 3000

      feature_dim: ${model.texture.non_rigid_dim}
      latent_dim: 0
      pose_encoder:
        num_joints: 24
        rel_joints: false
        dim_per_joint: 6
        out_dim: -1

      hashgrid:
        n_levels: 16
        n_features_per_level: 2
        log2_hashmap_size: 16
        base_resolution: 16
        per_level_scale: 1.447269237440378 # max reso 4096
        max_resolution: 2048

      mlp:
        n_neurons: 128
        n_hidden_layers: 3
        skip_in: []
        cond_in: [ 0 ]
        multires: 0

        last_layer_init: false

opt:
#  lambda_nr_xyz: 1e-2
  lambda_nr_xyz: 0.
#  lambda_nr_scale: 1e-4
  lambda_nr_scale: 0.
  lambda_nr_rot: 0.
  non_rigid_lr: 1e-3
  nr_latent_lr: 1e-3