# @package _global_

dataset_name: zju_386_mono

dataset:
  name: zjumocap
  root_dir: "../../data/ZJUMoCap"
  subject: CoreView_386
  refine: false

  train_views: [ '1' ]
  val_views: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['1']

  train_frames: [ 0, 540, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 540, 30]
    video: [0, 540, 1]
    all: [0, 540, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false